# Generated by Django 4.2.7 on 2023-11-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('telegram', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('citizenship', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
                ('birth_date', models.DateField()),
                ('native_language', models.CharField(max_length=255)),
                ('other_languages_and_levels', models.CharField(max_length=255)),
                ('contacts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='privet.contacts')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='privet.userinfo'),
        ),
    ]
