# Generated by Django 4.2.7 on 2023-12-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0004_remove_buddy_id_remove_student_id_alter_buddy_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='privet.student')),
            ],
        ),
        migrations.CreateModel(
            name='ArrivalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('other_students', models.ManyToManyField(related_name='other_students', to='privet.student')),
            ],
        ),
        migrations.AddField(
            model_name='buddy',
            name='buddy_arrivals',
            field=models.ManyToManyField(related_name='buddy', to='privet.buddyarrival'),
        ),
        migrations.AddField(
            model_name='student',
            name='arrival_booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='privet.arrivalbooking'),
        ),
    ]
