# Generated by Django 4.2.7 on 2023-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0005_buddyarrival_arrivalbooking_buddy_buddy_arrivals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrivalbooking',
            name='other_students',
            field=models.ManyToManyField(blank=True, related_name='other_students', to='privet.student'),
        ),
    ]
