# Generated by Django 4.2.7 on 2023-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0006_alter_arrivalbooking_other_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='other_languages_and_levels',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
