# Generated by Django 4.2.7 on 2023-12-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0007_alter_userinfo_other_languages_and_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyarrival',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='privet.student'),
        ),
    ]
