# Generated by Django 4.2.7 on 2023-12-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0009_arrivalbooking_arrival_point_arrivalbooking_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOnlyViewFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(blank=True, max_length=255, null=True)),
                ('study_program', models.CharField(blank=True, max_length=255, null=True)),
                ('last_visa_expiration', models.DateField(blank=True, null=True)),
                ('accommodation', models.CharField(blank=True, max_length=255, null=True)),
                ('buddys_comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='only_view',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='privet.studentonlyviewfields'),
        ),
    ]
