# Generated by Django 4.2.7 on 2023-12-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0010_studentonlyviewfields_student_only_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teamlead',
            field=models.BooleanField(default=False),
        ),
    ]
