# Generated by Django 4.2.7 on 2024-01-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0012_student_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
