# Generated by Django 4.2.7 on 2024-01-04 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0013_buddy_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddy',
            name='buddy_status',
        ),
        migrations.RemoveField(
            model_name='buddy',
            name='is_confirmed',
        ),
    ]
