# Generated by Django 4.2.7 on 2024-01-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0014_remove_buddy_buddy_status_remove_buddy_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddy',
            name='buddy_status',
            field=models.BooleanField(default=False),
        ),
    ]
