# Generated by Django 4.2.7 on 2024-01-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0016_buddy_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='sex',
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=255),
            preserve_default=False,
        ),
    ]
