# Generated by Django 4.2.7 on 2024-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0020_rename_other_languages_and_levels_otherlanguagesandlevels_other_language_and_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherlanguagesandlevels',
            name='other_language_and_level',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
