# Generated by Django 4.2.7 on 2024-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0022_passcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherlanguagesandlevels',
            name='other_language_and_level',
        ),
        migrations.AddField(
            model_name='otherlanguagesandlevels',
            name='language',
            field=models.CharField(default='english', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherlanguagesandlevels',
            name='level',
            field=models.CharField(default='A1', max_length=255),
            preserve_default=False,
        ),
    ]
