# Generated by Django 4.2.7 on 2024-01-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0023_remove_otherlanguagesandlevels_other_language_and_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tickets')),
            ],
        ),
        migrations.AddField(
            model_name='arrivalbooking',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='privet.ticket'),
        ),
    ]
