# Generated by Django 4.2.7 on 2024-01-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0024_ticket_arrivalbooking_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyarrival',
            name='buddy_arrival_status',
            field=models.BooleanField(default=False),
        ),
    ]
