# Generated by Django 4.2.7 on 2024-01-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0025_buddyarrival_buddy_arrival_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
