# Generated by Django 4.2.7 on 2024-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0027_alter_student_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
