# Generated by Django 4.2.7 on 2024-01-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privet', '0031_alter_userinfo_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
